sudo: required

language: go

go:
  - 1.5

services:
  - docker

before_install:
  - go get -t .
  - go get -t ./yokeadm
  - go build
  - go build -o ./yokeadm/yokeadm ./yokeadm
  - docker build -t nanobox/yoke .

script: ./test.sh
